In [1]:
import os
import random
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt
import seaborn as sns 
import matplotlib.cm as cm
from matplotlib import rcParams
import nltk 
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.tokenize import RegexpTokenizer
from nltk.stem.isri import ISRIStemmer
from collections import Counter 
import itertools
import string
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from joblib import dump, load

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\luche\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
import pandas as pd

df = pd.read_pickle('./data/processed_data.pkl')
#dataTest = pd.read_table('../input/semevalll/SemEval2017-test.txt', usecols=[1,2], encoding='utf-8', names=['sentiment', 'tweet'])                   
#combine = [dataTrain,dataTest]
df

,id,sentiment,tweet,label
0,628949369883000832,negative,"[dear, newOofice, Mac, great, al, Lync, update...",-1
1,628976607420645377,negative,"[make, system, doesnt, eat, frigin, discs, Thi...",-1
2,629023169169518592,negative,"[I, may, ignorant, isue, celebrate, parental, ...",-1
3,629179223232479232,negative,"[Thanks, I, may, switching]",-1
4,629186282179153920,neutral,"[If, I, make, game, windows, Universal, Ap, Wi...",0
...,...,...,...,...
5863,639855845958885376,positive,"[ok, god, know, Punting, MetLife, December, ta...",1
5864,639979760735662080,neutral,"[everyone, sat, around, metlife, anoying, didn...",0
5865,640196838260363269,neutral,"[giants, niners, fans, would, wana, go, sunday...",0
5866,640975710354567168,positive,"[Anybody, want, ticket, tomorow, Colombia, vs,...",1
5867,641034340068143104,neutral,"[Mendez, told, hed, drive, MetLife, Sunday, My...",0